---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterinfos.clusterconfig.wimsey.us
spec:
  group: clusterconfig.wimsey.us
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                oidc:
                  type: object
                  properties:
                    issuerUri:
                      type: string
                    clientId:
                      type: string
                    clientSecret:
                      type: string
                    caCertUri:
                      type: string
  scope: Cluster
  names:
    plural: clusterinfos
    singular: clusterinfo
    kind: ClusterInfo

---
apiVersion: clusterconfig.wimsey.us/v1
kind: ClusterInfo
metadata:
  name: default
spec:
  oidc:
    issuerUri: https://accounts.google.com
    clientId: 1041391019449-oa5p8pd37qg006a2hiv9pnp05h2ecen5.apps.googleusercontent.com

##oc edit clusterrole system:discovery
##---
##apiVersion: rbac.authorization.k8s.io/v1
##kind: ClusterRole
##metadata:
##  annotations:
##    rbac.authorization.kubernetes.io/autoupdate: "true"
##  creationTimestamp: "2022-01-13T03:43:38Z"
##  labels:
##    kubernetes.io/bootstrapping: rbac-defaults
##  name: system:discovery
##  resourceVersion: "4664578"
##  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/system%3Adiscovery
##  uid: 0c69a4af-e0ae-4008-8e26-eea683df5bd5
##rules:
#  - apiGroups:
#      - clusterconfig.wimsey.us
#    resources:
#      - clusterinfos
#    verbs:
#      - get
#      - watch
#      - list
##  - nonResourceURLs:
##      - /api
##      - /api/*
##      - /apis
##      - /apis/*
##      - /healthz
##      - /livez
##      - /openapi
##      - /openapi/*
##      - /readyz
##      - /version
##      - /version/
##    verbs:
##      - get
##

#oc edit clusterrolebinding system:discovery
#---
### Please edit the object below. Lines beginning with a '#' will be ignored,
### and an empty file will abort the edit. If an error occurs while saving this file will be
### reopened with the relevant failures.
###
##apiVersion: rbac.authorization.k8s.io/v1
##kind: ClusterRoleBinding
##metadata:
##  annotations:
##    rbac.authorization.kubernetes.io/autoupdate: "true"
##  creationTimestamp: "2022-01-13T03:43:40Z"
##  labels:
##    kubernetes.io/bootstrapping: rbac-defaults
##  name: system:discovery
##  resourceVersion: "4660405"
##  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/system%3Adiscovery
##  uid: dfe80df2-36f2-48ba-b0ef-9dc19e5d5322
##roleRef:
##  apiGroup: rbac.authorization.k8s.io
##  kind: ClusterRole
##  name: system:discovery
##subjects:
##  - apiGroup: rbac.authorization.k8s.io
##    kind: Group
##    name: system:authenticated
#  - apiGroup: rbac.authorization.k8s.io
#    kind: User
#    name: system:anonymous
# curl https://k8s-api.wimsey.us/apis/clusterconfig.wimsey.us/v1/clusterinfos/default

# curl -k https://localhost:16443/apis/clusterconfig.wimsey.us/v1/clusterinfos/default
