---
apiVersion: v1
kind: Secret
metadata:
  name: vault-aws-kms-key
  namespace: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: master
stringData:
  AWS_ACCESS_KEY_ID: 'Get access key from here - https://us-east-1.console.aws.amazon.com/iam/home?region=us-east-1#/users/details/vault-kms?section=security_credentials'
  AWS_SECRET_ACCESS_KEY: 'Get access key from here - https://us-east-1.console.aws.amazon.com/iam/home?region=us-east-1#/users/details/vault-kms?section=security_credentials'
