---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secrets
  namespace: kube-oidc
  labels:
    app.kubernetes.io/name: oidc-proxy
    app.kubernetes.io/instance: master
stringData:
  oidc_client_id: "From a client created here - https://console.cloud.google.com/auth/clients"
  oidc_client_secret: "From a client created here - https://console.cloud.google.com/auth/clients"
  oauth_cookie_secret: "Randomly generated - can be changed at any time but breaks existing clients on change"
